# errors during exectuion
try:
    print(x)
except:
    print("NameError occurred")
finally:
    print("success")

try:
 num1 = 20
 num2 = 10
 print(num1/num2)
except:
    print("ZeroDivisonError occured")

# User-defined function
def sum(first,second):
    return first + second





print(sum(10,20))



